---
title: "Global Sea Level Rise"
author: "Maximilian Stock"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
```

```{r}
months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

NorthernHem <- list()
SouthernHem <- list()

for (i in months) {
  NorthernHem[[i]] <- read_excel("Sea_Ice_Index_Monthly_Data_with_Statistics_G02135_v3.0.xlsx",
    sheet = paste0(i,"-NH"), skip = 8, range = "B10:S53")
}

for (i in months) {
  SouthernHem[[i]] <- read_excel("Sea_Ice_Index_Monthly_Data_with_Statistics_G02135_v3.0.xlsx",
    sheet = paste0(i,"-SH"), skip = 8, range = "B10:S53")
}

bindedNH <- bind_rows(NorthernHem)
bindedSH <- bind_rows(SouthernHem)

master <- bind_rows(bindedNH, bindedSH) %>% 
  clean_names()

```

```{r}
sheets <- c("Land", "Population", "GDP", "Agriculture", "UrbanExtent")

for (i in sheets) {
  assign(paste0("imp", i), read_excel("new_slr-impacts_nov2010.xls", 
    sheet = i))
}

impAgriculture <- impAgriculture %>% 
  clean_names()
impGDP <- impGDP%>% 
  clean_names()
impLand <- impLand%>% 
  clean_names()
impPopulation <- impPopulation%>% 
  clean_names()
impUrbanExtent <- impUrbanExtent %>% 
  clean_names()

```

```{r}
tempAnomaliesNH <- read_excel("tempAno.xlsx", sheet = "Sheet1", col_types = c("numeric", 
    "numeric")) %>% 
  clean_names() %>% 
  rename("N" = "nh_value_celsius")

tempAnomaliesSH <-read_excel("tempAno.xlsx", sheet = "Sheet2", col_types = c("numeric", 
    "numeric")) %>% 
  clean_names() %>% 
  rename("S" = "sh_value_celsius")

tempAnomaliesGlobal <- left_join(tempAnomaliesNH, tempAnomaliesSH, by = "year_jan")
tempAnomaliesGlobal <- tempAnomaliesGlobal %>% 
  pivot_longer(cols = c("N", "S"), values_to = "tempAnomaly") %>% 
  rename("hemisphere" = "name", "year" = "year_jan")
```

```{r}

yearlyIceMeans <- master %>% 
  select(-reordered) %>% 
  drop_na() %>% 
  group_by(year, hemisphere) %>% 
  summarise(meanEx = mean(extent)) %>% 
  left_join(tempAnomaliesGlobal, by = c("year", "hemisphere")) 
  


p1 <- yearlyIceMeans %>% 
  ggplot(aes(x = year)) +
    geom_line(aes(y = meanEx, color = hemisphere)) +
    scale_color_manual(values = c("#2246c7", "#1ba2ea")) +
    theme_classic() +
    theme(panel.grid.major.y = element_line(colour = "grey80"), legend.position = "top")


p2 <- yearlyIceMeans %>% 
  ggplot(aes(x = year)) +
    geom_col(aes(y = tempAnomaly, fill = hemisphere), position = "dodge") +
    scale_fill_manual(values = c("#2246c7", "#1ba2ea")) +
    theme_classic() +
    theme(panel.grid.major.y = element_line(colour = "grey80"), legend.position = "none")
    

gridExtra::grid.arrange(p1, p2)

```

```{r}
years <- c("1980", "1990", "2000", "2010", "2020")

p2 <- master %>% 
  mutate(year = factor(year))

ggplot(data = p2 %>% 
         select(-reordered) %>% 
         drop_na() %>% 
         filter(year %in% years), aes(x = month, y = extent)) +
  geom_line(aes(colour = year)) +
  facet_wrap(vars(hemisphere), nrow = 2) +
  scale_color_manual(values = c("#c1cef7", "#a1b0e3" ,"#607ce0", "#2246c7",  "#061c2b")) +
  theme_classic() 



```
```{r}

impGDPBase <- impGDP %>% 
  mutate(perc5 = x5_meter/total_gdp) %>% 
  rename("region" = "country_2")
```

```{r}
require(maps)
require(viridis)
theme_set(
  theme_void()
  )
```

```{r}
world_map <- map_data("world")
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "white")
```

```{r}
# Some EU Contries
some.eu.countries <- c("Argentina", "Bahamas", "Belize", "Brazil", "Chile", 
 "Colombia"      ,        "Costa Rica"       ,     "Cuba",   "Dominican Republic"   , "Ecuador" ,             
"El Salvador"      ,     "French Guiana"    ,     "Guatemala"      ,       "Guyana", "Haiti", 
 "Honduras"      ,        "Jamaica"           ,    "Mexico", "Suriname"  ,           "Nicaragua"            ,"Peru",   "Panama", "Puerto Rico", "Uruguay"  ,             "Venezuela")
# Retrievethe map data
some.eu.maps <- map_data("world", region = some.eu.countries) %>% 
  left_join(impGDPBase, by = "region")


library(ggrepel)

# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))

ggplot(some.eu.maps, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, fill = perc5)) +

  
    geom_text_repel(box.padding = 0.5, max.overlaps = Inf, aes(label = region), data = region.lab.data, color = "black", size = 2, hjust = 0.5) +
    scale_fill_gradient(low = "#c1cef7", high = "#061c2b")+
  coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs ")
  # scale_fill_viridis_d()+
  # theme_void()+
  # theme(legend.position = "none")

```




