---
title: "Global Sea Level Rise"
author: "Maximilian Stock"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(aTSA)
library(TSA)
library(forecast)
```

```{r}
months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

NorthernHem <- list()
SouthernHem <- list()

for (i in months) {
  NorthernHem[[i]] <- read_excel("Sea_Ice_Index_Monthly_Data_with_Statistics_G02135_v3.0.xlsx",
    sheet = paste0(i,"-NH"), skip = 8, range = "B10:S53")
}

for (i in months) {
  SouthernHem[[i]] <- read_excel("Sea_Ice_Index_Monthly_Data_with_Statistics_G02135_v3.0.xlsx",
    sheet = paste0(i,"-SH"), skip = 8, range = "B10:S53")
}

bindedNH <- bind_rows(NorthernHem)
bindedSH <- bind_rows(SouthernHem)

master <- bind_rows(bindedNH, bindedSH) %>% 
  clean_names()


```


```{r, ice&sealevel_data_operating}
sea_level<-read.csv("sealevel.csv")

date<-data.frame(matrix(unlist(strsplit(sea_level$Day,"-")),ncol=3, byrow = T))
colnames(date)<-c("year","month","day")
sea_level_model<-sea_level %>%
  select(-Day)%>%
  mutate(year = as.integer(date$year), month = as.integer(date$month))%>%
  filter(year >= 1979)%>%
  select(sea_level_rise_average, year, month)

ice_model<-master %>%
  filter(month %in% c(1,4,7,10), hemisphere =="N")%>%
  select(year, month, extent, area, extent_anomaly)

```


```{r, tempdatainmprt}

temp<-read.csv("TempNorth.csv")
temp_data<-data.frame(matrix(unlist(strsplit(temp$Year.Value,",")),ncol=2, byrow = T))
colnames(temp_data)<-c("date","tempN")
temp_model<-temp_data %>%
  mutate(year = as.integer(substr(date,1,4)),
         month = as.integer(substr(date,5,6)))%>%
  select(-date)%>%
  filter(year >=1979, month %in% c(1,4,7,10))

```

```{r, model_data_merger}

model_data_first<- left_join(temp_model,ice_model, by=c("year","month"))
model_data<-left_join(model_data_first,sea_level_model,by=c("year","month"))
model_data$tempN<-as.numeric(model_data$tempN)
model_data<-model_data%>%
  filter(year<=2020)

```

```{r, time_series}

dt<-ts(as.numeric(model_data$sea_level_rise_average),start = 1979,frequency=4)
plot(dt)
plot(diff(dt))
plot(diff(diff(dt)))
aTSA::adf.test(diff(dt))
acf(diff(diff(dt)))
pacf(diff(diff(dt)))
#according to the ACF and PACF assessment, we decided to build up arima（0，2，2）model
fit1<-stats::arima(dt,order = c(2,2,6))
fit1
#Using box-test to evaluate the model
Box.test(fit1$residuals)
#For fit one, we can forecast the following 10 years' Sea Level Rise
fore1<-forecast::forecast(fit1,h=40)
plot(fore1)
fore1

#adding seasonal trend to our model and build up a HoltWinters Time-series Model
fit2<- HoltWinters(dt,gamma=T)
plot(decompose(dt))
fore2<-forecast(fit2,h=400)
plot(fore2)
fore2

```

```{r, regression}
library(GGally)
model_data %>% 
  select(tempN, extent, area, extent_anomaly, sea_level_rise_average) %>% 
  ggpairs(aes(alpha = 0.2))

model1<-lm( sea_level_rise_average ~ tempN+extent_anomaly , data = model_data)
summary(model1)
```

```{r}
sheets <- c("Land", "Population", "GDP", "Agriculture", "UrbanExtent")

for (i in sheets) {
  assign(paste0("imp", i), read_excel("new_slr-impacts_nov2010.xls", 
    sheet = i))
}

impAgriculture <- impAgriculture %>% 
  clean_names()
impGDP <- impGDP%>% 
  clean_names()
impLand <- impLand%>% 
  clean_names()
impPopulation <- impPopulation%>% 
  clean_names()
impUrbanExtent <- impUrbanExtent %>% 
  clean_names()

```

```{r}
tempAnomaliesNH <- read_excel("tempAno.xlsx", sheet = "Sheet1", col_types = c("numeric", 
    "numeric")) %>% 
  clean_names() %>% 
  rename("N" = "nh_value_celsius")

tempAnomaliesSH <-read_excel("tempAno.xlsx", sheet = "Sheet2", col_types = c("numeric", 
    "numeric")) %>% 
  clean_names() %>% 
  rename("S" = "sh_value_celsius")

tempAnomaliesGlobal <- left_join(tempAnomaliesNH, tempAnomaliesSH, by = "year_jan")
tempAnomaliesGlobal <- tempAnomaliesGlobal %>% 
  pivot_longer(cols = c("N", "S"), values_to = "tempAnomaly") %>% 
  rename("hemisphere" = "name", "year" = "year_jan")
```

```{r}

yearlyIceMeans <- master %>% 
  select(-reordered) %>% 
  drop_na() %>% 
  group_by(year, hemisphere) %>% 
  summarise(meanEx = mean(extent)) %>% 
  left_join(tempAnomaliesGlobal, by = c("year", "hemisphere")) 
  


p1 <- yearlyIceMeans %>% 
  ggplot(aes(x = year)) +
    geom_line(aes(y = meanEx, color = hemisphere)) +
    scale_color_manual(values = c("#2246c7", "#1ba2ea")) +
    theme_classic() +
    theme(panel.grid.major.y = element_line(colour = "grey80"), legend.position = "top")


p2 <- yearlyIceMeans %>% 
  ggplot(aes(x = year)) +
    geom_col(aes(y = tempAnomaly, fill = hemisphere), position = "dodge") +
    scale_fill_manual(values = c("#2246c7", "#1ba2ea")) +
    theme_classic() +
    theme(panel.grid.major.y = element_line(colour = "grey80"), legend.position = "none")
    

gridExtra::grid.arrange(p1, p2)

```

```{r}
years <- c("1980", "1990", "2000", "2010", "2020")

p2 <- master %>% 
  mutate(year = factor(year))

ggplot(data = p2 %>% 
         select(-reordered) %>% 
         drop_na() %>% 
         filter(year %in% years), aes(x = month, y = extent)) +
  geom_line(aes(colour = year)) +
  facet_wrap(vars(hemisphere), nrow = 2) +
  scale_color_manual(values = c("#c1cef7", "#a1b0e3" ,"#607ce0", "#2246c7",  "#061c2b")) +
  theme_classic() 



```
```{r}


impGDPBase <- impGDP %>% 
  mutate(perc1 = x1_meter/total_gdp) %>% 
  rename("region" = "country_2")
```

```{r}
require(maps)
require(viridis)
theme_set(
  theme_void()
  )
```

```{r}
world_map <- map_data("world")
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "white")
```

```{r, fig.height=8, fig.width=12}
# Some EU Contries
some.eu.countries <- c("Argentina", "Bahamas", "Belize", "Brazil", "Chile", 
 "Colombia"      ,        "Costa Rica"       ,     "Cuba",   "Dominican Republic"   , "Ecuador" ,             
"El Salvador"      ,     "French Guiana"    ,     "Guatemala"      ,       "Guyana", "Haiti", 
 "Honduras"      ,        "Jamaica"           ,    "Mexico", "Suriname"  ,           "Nicaragua"            ,"Peru",   "Panama", "Puerto Rico", "Uruguay"  ,             "Venezuela")
# Retrievethe map data
some.eu.maps <- map_data("world") %>% 
  left_join(impGDPBase, by = "region")

library(ggrepel)

# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))

ggplot(some.eu.maps, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, fill = perc1), color = "#061c2b", size = 0.2) +

  
    # geom_text_repel(box.padding = 0.5, max.overlaps = Inf, aes(label = region), data = region.lab.data, color = "black", size = 2, hjust = 0.5) +
    scale_fill_gradient(low = "white", high = "#2246c7", na.value = "white")+
  coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs ") + 
  labs(fill = "GDP impacted") 
  # scale_fill_viridis_d()+
  # theme_void()+
  # theme(legend.position = "none")

```


```{r}
isoContinent <- read_excel("isoContinent.xlsx")

isoContinent <- isoContinent %>% 
  clean_names() %>% 
  rename("country_1" = "alpha_3", "cont" = "region")

impGDPBaseJoined <- impGDPBase %>% 
  left_join(isoContinent[, c("country_1", "cont", "sub_region")], by = "country_1")

outliers = c("VNM", "EGY", "SUR", "MRT", "BEN", "GUY", "BHS")

bps <- impGDPBaseJoined %>%
  mutate(outLable = if_else(country_1 %in% outliers, region, "")) 


ggplot(bps, aes(x = perc1, y = fct_relevel(sub_region, "Melanesia","Sub-Saharan Africa", "Southern Asia",
             "	
Melanesia", 
            "Northern Africa","Latin America and the Caribbean", "Western Asia",
              "South-eastern Asia", "Eastern Asia"))) +
    geom_boxplot(outlier.color = "#2246c7", color = "#061c2b") +
  geom_text_repel(aes(label = outLable), size = 3, color = "#061c2b", box.padding = 0.5, max.overlaps = Inf)+
    theme_classic() +
    theme(panel.grid.major.x = element_line(colour = "grey80"), axis.text.y = element_text( size = 6)) +
    scale_x_continuous(labels = scales::percent) +
    labs(y = "", x = "")


```


```{r, fig.height=3, fig.width=5}
impPopulationBase <- impPopulation %>% 
  mutate("1 Meter" = x1_meter / country_3, "2 Meters" = x2_meter / country_3, "3 Meters" = x3_meter / country_3, "4 Meters"= x4_meter / country_3, "5 Meters" = x5_meter / country_3) %>% 
  filter(country_1 == "VNM") %>% 
  pivot_longer(cols = c("1 Meter", "2 Meters", "3 Meters", "4 Meters", "5 Meters"), names_to = "scenario", values_to = "popPercImp")

ggplot(impPopulationBase, aes(x = popPercImp, y = fct_reorder(scenario, -popPercImp))) +
  geom_col(fill = "grey90") +
  theme_classic() +
  geom_label(aes(label = scales::percent(popPercImp))) +
   # theme(axis.title.x=element_blank(),
   #      axis.text.x=element_blank(),
   #      axis.ticks.x=element_blank())+
  labs(y = "SLR Scenario") +
  xlim(0,1)


```

```{r}
some.eu.countries <- c("Argentina", "Bahamas", "Belize", "Brazil", "Chile", 
 "Colombia"      ,        "Costa Rica"       ,     "Cuba",   "Dominican Republic"   , "Ecuador" ,             
"El Salvador"      ,     "French Guiana"    ,     "Guatemala"      ,       "Guyana", "Haiti", 
 "Honduras"      ,        "Jamaica"           ,    "Mexico", "Suriname"  ,           "Nicaragua"            ,"Peru",   "Panama", "Puerto Rico", "Uruguay"  ,             "Venezuela")
# Retrievethe map data
some.eu.maps <- map_data("world", region  = "Vietnam")

library(ggrepel)

# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))

ggplot(some.eu.maps, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill = "#2246c7", color = "#2246c7", size = 0.2) +
  coord_sf(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs ") +
  theme(panel.background = element_rect(fill = "#061c2b"))
```


```{r, fig.height=3, fig.width=5}
impLandBase <- impLand %>% 
  mutate("1 Meter" = x1_meter / country_area, "2 Meters" = x2_meter / country_area, "3 Meters" = x3_meter / country_area, "4 Meters"= x4_meter / country_area, "5 Meters" = x5_meter / country_area) %>% 
  filter(country_1 == "BHS") %>%
  rename("1" = "1 Meter", "2" = "2 Meters", "3" = "3 Meters", "4" = "4 Meters", "5" = "5 Meters") %>% 
  pivot_longer(cols = c("1", "2", "3", "4", "5"), names_to = "scenario", values_to = "landPercImp") %>% 
  mutate(scenario = as.integer(scenario))

ggplot(impLandBase, aes(x = scenario, y = landPercImp)) +
  geom_area( colour = "#2246c7", fill ="#2246c7", alpha = 0.4)+
  geom_point(colour = "#2246c7")+
  theme_classic() +
  theme(panel.grid.major.y = element_line(colour = "grey80", size = 0.2)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  labs(y = "", x = "")



ggplot(impLandBase, aes(x=scenario, y=landPercImp)) +
  geom_segment( aes(x=scenario, xend=scenario, y=0, yend=landPercImp), color="grey80") +
  # geom_line(color = "grey80")+
  geom_point( color="#2246c7", size=4) +
  theme_classic() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  geom_text(aes(label = scales::percent(landPercImp)), vjust =- 1.5, size = 3)+
  xlab("") +
  xlim(0,12)+
  ylab("Value of Y") +
  scale_y_continuous(labels = scales::percent, limits = c(0,0.7))

```
```{r, fid.width = 5, fig.height=2}

impGDPBaseNew <- impGDP %>% 
  mutate("1 Meter" = x1_meter / total_gdp, "2 Meters" = x2_meter / total_gdp, "3 Meters" = x3_meter / total_gdp, "4 Meters"= x4_meter / total_gdp, "5 Meters" = x5_meter / total_gdp) %>% 
  filter(country_1 %in% c("BHS")) %>%
  rename("1" = "1 Meter", "2" = "2 Meters", "3" = "3 Meters", "4" = "4 Meters", "5" = "5 Meters") %>% 
  pivot_longer(cols = c("1", "2", "3", "4", "5"), names_to = "scenario", values_to = "gdpPercImp") %>% 
  mutate(scenario = as.factor(scenario)) %>% 
  filter(scenario %in% c("1", "5"))

ggplot(impGDPBaseNew, aes(y = scenario, x = gdpPercImp)) +
  geom_col(aes(fill = scenario)) +
  theme_classic() +
  scale_x_continuous(labels = scales::percent) +
  scale_fill_manual(values = c( "#2146C7","#17379A")) +
  theme(legend.position = "none")


```

